name: check Python 3.5 compatibility
on: [push, pull_request]
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    container: sciapp/python-testing:latest-ubuntu-20.04
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Setup simple-term-menu on Python 3.5
      run: python3.5 -m pip install .
    - name: Run a simple-term-menu check on Python 3.5
      run: python3.5 -m simple_term_menu --version
